# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Thibault Laurens
tagline:          "Yet another developer\'s blog"
description:      "Yet another developer\'s blog. Some notes and links to other websites."
url:              "https://thibaultlaurens.github.io"
baseurl:          /

author:
  name:           "Thibault Laurens"
  url:            "https://thibaultlaurens.github.io"

plugins:          [jekyll-paginate]
paginate:         5

collections:
  courses:
    output: true
    permalink: /:collection/:path

social:
  github:        "https://github.com/ThibaultLaurens"
  blog:          "https://github.com/ThibaultLaurens/thibaultlaurens.github.io"
  linkedin:      "https://www.linkedin.com/in/thibaultlaurens"
  flickr:        "https://www.flickr.com/photos/tlaurens"
  website:       "https://thibaultlaurens.com"

external:
  analytics: 'UA-37401574-1'
  disqus: 'thibaultlaurens'
